version: '3'

services:
    frontend:
        image: 192.168.1.136:9005/lake_stats_front:latest
        container_name: lake_stats_front
        ports:
            - "9010:80"
            - "9011:443"
        restart: unless-stopped